apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: np2
spec:
  template:
    spec:
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m5d.xlarge", "c6a.large"]
