apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: simple-home
          image: vietaws/eks:home
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: home-svc
  labels:
    app: home-app
spec:
  type: NodePort
  selector:
    app: home
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort: 31989
