# Annotations Reference:  https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/ingress/spec/

# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/ingress/annotations/

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 08-alb-basics
  labels:
    app: home-app
  annotations:
    # Ingress Core Settings
    # kubernetes.io/ingress.class: "alb" | deprecated
    alb.ingress.kubernetes.io/load-balancer-name: 08-alb-basics
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/target-type: instance #| instance | ip
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
spec:
  ingressClassName: aws-ingress-class
  defaultBackend:
    service:
      name: home-svc
      port:
        number: 8080
