apiVersion: v1
kind: Service
metadata:
  name: service1 # Name of the Service
spec:
  type: NodePort
  selector:
    # Loadbalance traffic across Pods matching this label selector
    tier: front-end
  # Accept traffic sent to port 80
  ports:
    - name: http
      port: 8081 # Service Port
      targetPort: 8080 # Container Port
      nodePort: 31988 # NodePort
