apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-deploy-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-deploy-sc
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: simple-home
          image: vietaws/eks:home
          ports:
            - containerPort: 8080
          command: ['/bin/sh']
          args:
            [
              '-c',
              'while true; do echo "from Deployment. Hostname: $(hostname)" >>
              /app-logs/out.txt; sleep 5; done',
            ]
          volumeMounts:
            - name: persistent-storage
              mountPath: /app-logs
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-deploy-pvc
