apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-demo-deployment
  labels:
    app: vpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpa
  template:
    metadata:
      labels:
        app: vpa
    spec:
      containers:
        - name: vpa
          image: vietaws/eks:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "5m"
              memory: "5Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-demo-service
  labels:
    app: vpa
spec:
  type: NodePort
  selector:
    app: vpa
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31232
