apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: io2
  blockExpress: 'true' # string type
  iops: '4000' # result: 2,000 iops due to instance type is not supported io2 block express
  # iopsPerGB: '1000' # string type # cannot use both with iops
  encrypted: 'true' # string type
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete # Values: Retain | Delete (Default())
allowVolumeExpansion: true # boolean
volumeBindingMode: WaitForFirstConsumer
