apiVersion: v1
kind: Service
metadata:
  name: clb-demo
  labels:
    app: home-app
spec:
  type: LoadBalancer # Default - CLB
  selector:
    app: home-app
  ports:
    - port: 80
      targetPort: 8080
