apiVersion: v1
kind: Pod
metadata:
  name: efs-app-3
spec:
  containers:
    - name: app
      image: vietaws/eks:v3
      ports:
        - containerPort: 8080
          name: web
      command: ['/bin/sh']
      args:
        [
          '-c',
          'while true; do echo "from App3" >> /app-logs/out.txt; sleep 5; done',
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /app-logs
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim-2
