apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-ns-pvc2
  namespace: ns2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-ns-sc
  volumeName: efs-pv2
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  namespace: ns2
  labels:
    app: home
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: simple-home
          image: vietaws/eks:home
          ports:
            - containerPort: 8080
          command: ['/bin/sh']
          args:
            [
              '-c',
              'while true; do echo "from Deployment NS2. Hostname: $(hostname)"
              >> /ns-logs/out.txt; sleep 5; done',
            ]
          volumeMounts:
            - name: persistent-storage
              mountPath: /ns-logs
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-ns-pvc2
