apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  # annotations:
  #   pv.kubernetes.io/bind-completed: 'yes'
  #   pv.kubernetes.io/bound-by-controller: 'yes'
  #   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  #   volume.kubernetes.io/selected-node: ip-192-168-99-28.ap-southeast-1.compute.internal
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  blockExpress: 'false' # string type
  iopsPerGB: '100' # string type. Min IOPS gp3: 3,000
  encrypted: 'true' # string type
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete # Values: Retain | Delete (Default())
allowVolumeExpansion: true # boolean
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - ap-southeast-1b
