apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: home
          image: vietaws/eks:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "5m"
              memory: "5Mi"
            limits:
              cpu: "10m"
              memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: home-svc
  labels:
    app: home
spec:
  selector:
    app: home
  ports:
    - port: 80
      targetPort: 8080
