apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo-deployment
  labels:
    app: hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
        - name: hpa
          image: vietaws/eks:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '500Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-service
  labels:
    app: hpa
spec:
  type: NodePort
  selector:
    app: hpa
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31231
