apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instance-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  resources:
    requests:
      storage: 200Gi
