apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-108-90.ap-southeast-1.compute.internal
      containers:
        - name: simple-app
          image: vietaws/eks:home
          command: ['/bin/sh']
          args:
            [
              '-c',
              'while true; do echo $(date) >> /data/logs.txt; sleep 5; done',
            ]
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
          ports:
            - containerPort: 8080
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: instance-storage-pvc
